[pytest]
pythonpath = .
addopts = -ra -q --strict-config --strict-markers --maxfail=1 --cov=tests
filterwarnings = 
    error
    ignore::DeprecationWarning:pkg_resources
    ignore::DeprecationWarning:numpy

testpaths = tests 
xfail_strict = True

[coverage:run]
branch = True
source = .
omit = 
    */__init__.py 
    */site-packages/*

[coverage:report]
fail_under=85
skip_covered=True
show_missing=True